# Generated by Django 4.2.11 on 2025-05-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0008_delete_saveconfigfiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControllerPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("ip_address", models.CharField(max_length=15)),
                ("controller_type", models.CharField(max_length=50)),
                ("command", models.CharField(blank=True, max_length=100)),
                ("options", models.CharField(blank=True, max_length=100)),
                ("value", models.CharField(blank=True, max_length=100)),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Detector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("io_board_input", models.CharField(max_length=10)),
                ("ki_pd_2", models.CharField(default="-", max_length=5)),
                ("ki_pd_16", models.CharField(max_length=10)),
                ("direction_number", models.IntegerField()),
                ("offset", models.CharField(default="-", max_length=5)),
                ("request", models.CharField(max_length=5)),
                ("gap", models.CharField(max_length=5)),
                ("ts_count", models.CharField(default="+", max_length=5)),
                ("unoccupied_alarm", models.CharField(max_length=10)),
                ("occupied_alarm", models.CharField(max_length=10)),
            ],
        ),
    ]
