# Generated by Django 4.2.11 on 2025-05-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0009_controllerpreset_detector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controllerpreset",
            name="command",
        ),
        migrations.RemoveField(
            model_name="controllerpreset",
            name="controller_type",
        ),
        migrations.RemoveField(
            model_name="controllerpreset",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="controllerpreset",
            name="options",
        ),
        migrations.RemoveField(
            model_name="controllerpreset",
            name="source",
        ),
        migrations.RemoveField(
            model_name="controllerpreset",
            name="value",
        ),
        migrations.AddField(
            model_name="controllerpreset",
            name="controllers_data",
            field=models.JSONField(default=list),
        ),
    ]
