# Generated by Django 4.2.11 on 2025-04-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toolkit", "0004_saveconfigfiles_trafficlightconfigurator"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trafficlightsobjects",
            old_name="adress",
            new_name="address",
        ),
    ]
